name: minikube
hosts: localhost
gather_facts: False
connection: local

  tasks:
    - name: create namespace
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
          name: lvillanueva
          labels:
          tipo: dev



    - name: PersistentVolume
      k8s:
        state: present
        definition:me
          apiVersion: v1 
          kind: PersistentVolume
          metadata:
             name: pv-volume
             namespace: lvillanueva
             labels:
               type: local
          spec:
            storageClassName: db
            capacity:
              storage: 10Gi
            accessModes:
              - ReadWriteOnce
            hostPath:
              path: "/mnt/data"   


    - name: PersistentVolumeClaim
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: pv-claim
            namespace: lvillanueva
          spec:
            storageClassName: db
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                 storage: 3Gi


    - name: deplybd
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: deployment-bdd
            namespace: lvillanueva
            labels:
             estado: "1"
          spec:
            selector:
              matchLabels:
                app: dbluis
                tier: data
            replicas: 1
            template:
              metadata:
                labels:
                  app: dbluis
                  tier: data
              spec:
                 containers:
                 - name: database
        image: 17240609/base:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: inmobiliaria
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: 

        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: pv-claim


    - name: deplyphp
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: deployment-app
            namespace: lvillanueva
            labels:
             estado: "1"
          spec:
            selector:
              matchLabels:
                app: dbluis
                tier: data
            replicas: 7
            template:
              metadata:
                labels:
                  app: dbluis
                  tier: data
              spec:
                containers:
                - name: my-app
                  image: 17240609/aplicacion:latest
                  ports:
                  - containerPort: 80
        


    - name: servicebd
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Service
          metadata:
            name: deployment-bd
            namespace: lvillanueva
            labels:
             estado: "1"
          spec:
            ports:
            -  port: 3306
               targetPort: 3306
               protocol: TCP
            selector:
              matchLabels:
                app: dbluis
                tier: mysql



    - name: servicephp
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Service
          metadata:
            name: deployment-app
            namespace: lvillanueva
            labels: 
             estado: "1"
          spec:
            ports:
            -  port: 80
               targetPort: 80
               protocol: TCP
            selector:
              matchLabels:
                app: dbluis


    - name: servicephp
      k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: ingress-apache
            namespace: lvillanueva
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /
          spec:
            rules:
            - host: app.lvillanueva.com
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: app
                      port:
                        number: 80
              


               